### ISSUE TITLE
Shopify - Snowflake : Invalid Identifier DEFAULT

### ISSUE THREAD

**Issue by aniljava** [airbytehq/airbyte#2128]
SQL Generator used for Snowflake is using naked field names in SQL generated. When the fieldname is same as one of the Snowflake identifiers it causes error. example: ` cast(default as boolean) as DEFAULT,`

One of the table in Shopify has "default" field which is triggers this error. Enclosing column name in double quotes would solve the problem. `cast("DEFAULT" as boolean) as "DEFAULT",`.

# Details of the error:

Sync failing with following error:

    2021-02-19 03:24:35 INFO (/tmp/workspace/10/2) LineGobbler(voidCall):69 - [33mDatabase Error in model AB2_DEFAULT_ADDRESS_1 (models/generated/airbyte_views/_AIRBYTE_AIRBYTE/AB2_DEFAULT_ADDRESS_1.sql)[0m
    2021-02-19 03:24:35 INFO (/tmp/workspace/10/2) LineGobbler(voidCall):69 -   000904 (42000): SQL compilation error: error line 28 at position 9
    2021-02-19 03:24:35 INFO (/tmp/workspace/10/2) LineGobbler(voidCall):69 -   invalid identifier 'DEFAULT'
    2021-02-19 03:24:35 INFO (/tmp/workspace/10/2) LineGobbler(voidCall):69 -   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_views/_AIRBYTE_AIRBYTE/AB2_DEFAULT_ADDRESS_1.sql

    # cat compiled/airbyte_utils/models/generated/airbyte_views/_AIRBYTE_AIRBYTE/AB2_DEFAULT_ADDRESS_2.sql

    select
        _AIRBYTE_CUSTOMER_1_HASHID,
        cast(ID as
        int
    ) as ID,
        cast(ZIP as
        varchar
    ) as ZIP,
        cast(CITY as
        varchar
    ) as CITY,
        cast(NAME as
        varchar
    ) as NAME,
        cast(PHONE as
        varchar
    ) as PHONE,
        cast(COMPANY as
        varchar
    ) as COMPANY,
        cast(COUNTRY as
        varchar
    ) as COUNTRY,
        cast(default as boolean) as DEFAULT,
        cast(ADDRESS1 as
        varchar
    ) as ADDRESS1,
        cast(ADDRESS2 as
        varchar
    ) as ADDRESS2,
        cast(PROVINCE as
        varchar
    ) as PROVINCE,
        cast(LAST_NAME as
        varchar
    ) as LAST_NAME,
        cast(FIRST_NAME as
        varchar
    ) as FIRST_NAME,
        cast(CUSTOMER_ID as
        int
    ) as CUSTOMER_ID,
        cast(COUNTRY_CODE as
        varchar
    ) as COUNTRY_CODE,
        cast(COUNTRY_NAME as
        varchar
    ) as COUNTRY_NAME,
        cast(PROVINCE_CODE as
        varchar
    ) as PROVINCE_CODE,
        _airbyte_emitted_at
    from "OPENBRIDGE_DATABASE"._AIRBYTE_AIRBYTE."AB1_DEFAULT_ADDRESS_2"

    -- DEFAULT_ADDRESS_2 from a/b/a/n/d/o/n/e/d/_/c/h/e/c/k/o/u/t/s///c/u/s/t/o/m/e/r///d/e/f/a/u/l/t/_/a/d/d/r/e/s/s

**Comment by ChristopheDuong** [comment]
The following docs from snowflake doesn't include 'default' in their reserved keyword...
https://docs.snowflake.com/en/sql-reference/reserved-keywords.html

That's why it didn't get treated, we just need to add it to our list of special keywords

**Comment by aniljava** [comment]
Instead of going via keyword route, we need to escape the field names. You are allowed to use identifiers in fieldname with snowflake or even sqlite. They need to be escaped.

**Comment by ChristopheDuong** [comment]
> Instead of going via keyword route, we need to escape the field names. You are allowed to use identifiers in fieldname with snowflake or even sqlite. They need to be escaped. I mean escape all fieldnames whether they are identifier or not. For example, if the the column name have space.

If you do that, then all your identifiers become case sensitive whereas what you call naked identifiers are case-insensitive

**Comment by aniljava** [comment]
Case sensitive is a good practice. Why do we need case in-sensitive ? Here airbyte is handling the DDLs as well as data insertions, why do we need case insensitivity ?

**Comment by ChristopheDuong** [comment]
Thanks for reporting this issue anyway!!

Sorry, we closed this issue as we already pushed/merge a quick fix for this case with the 'default' keyword that you encountered.

Would you mind opening another new ticket to request a feature where we always force quoted identifiers regardless of if it's possible to use them as unquoted or quoted?

That way, users would be able to make the call to enforce the case-sensitivity good practice or deal with case-insensitivity as they want?

On some warehouses, it is actually annoying/breaking if everything is quoted

**Comment by aniljava** [comment]
Please correct me if i am missing something here.

I pulled the latest mater branch with the changes from #2129 and verified i have updated version by checking current `airbyte-integrations/bases/base-normalization/normalization/transform_catalog/reserved_keywords.py`

The problem is still present. The generated SQL code is not changed. I am new to airbyte codebase, what is the expected outcome of having `DEFAULT` as an identifier. Will it quote `DEFAULT` where present or it will rename the fields.

    2021-02-19 20:49:42 INFO (/tmp/workspace/14/0) LineGobbler(voidCall):69 - invalid identifier 'DEFAULT'
    2021-02-19 20:49:42 INFO (/tmp/workspace/14/0) LineGobbler(voidCall):69 - compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_views/_AIRBYTE_AIRBYTE/AB2_ADDRESSES_2.sql
    2021-02-19 20:49:42 INFO (/tmp/workspace/14/0) LineGobbler(voidCall):69 -
    2021-02-19 20:49:42 INFO (/tmp/workspace/14/0) LineGobbler(voidCall):69 - Done. PASS=358 WARN=0 ERROR=6 SKIP=12 TOTAL=376
    2021-02-19 20:49:43 DEBUG (/tmp/workspace/14/0) DefaultNormalizationRunner(close):97 - Closing tap process
    2021-02-19 20:49:43 ERROR (/tmp/workspace/14/0) DefaultSyncWorker(run):117 - Normalization Failed.
    io.airbyte.workers.WorkerException: Normalization Failed.
    at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:114) [io.airbyte-airbyte-workers-0.14.4-alpha.jar:?]
    at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:48) [io.airbyte-airbyte-workers-0.14.4-alpha.jar:?]
    at io.airbyte.workers.wrappers.OutputConvertingWorker.run(OutputConvertingWorker.java:44) [io.airbyte-airbyte-workers-0.14.4-alpha.jar:?]
    at io.airbyte.workers.wrappers.JobOutputSyncWorker.run(JobOutputSyncWorker.java:32) [io.airbyte-airbyte-workers-0.14.4-alpha.jar:?]
    at io.airbyte.scheduler.WorkerRun.lambda$new$0(WorkerRun.java:53) [io.airbyte-airbyte-scheduler-0.14.4-alpha.jar:?]
    at io.airbyte.scheduler.WorkerRun.call(WorkerRun.java:61) [io.airbyte-airbyte-scheduler-0.14.4-alpha.jar:?]
    at io.airbyte.scheduler.WorkerRun.call(WorkerRun.java:42) [io.airbyte-airbyte-scheduler-0.14.4-alpha.jar:?]
    at io.airbyte.commons.concurrency.LifecycledCallable.execute(LifecycledCallable.java:114) [io.airbyte-airbyte-commons-0.14.4-alpha.jar:?]
    at io.airbyte.commons.concurrency.LifecycledCallable.call(LifecycledCallable.java:98) [io.airbyte-airbyte-commons-0.14.4-alpha.jar:?]
    at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
    at java.lang.Thread.run(Thread.java:832) [?:?]
    Suppressed: io.airbyte.workers.WorkerException: Tap process wasn't successful
    at io.airbyte.workers.normalization.DefaultNormalizationRunner.close(DefaultNormalizationRunner.java:100) ~[io.airbyte-airbyte-workers-0.14.4-alpha.jar:?]
    at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:109) [io.airbyte-airbyte-workers-0.14.4-alpha.jar:?]
    at io.airbyte.workers.DefaultSyncWorker.run(DefaultSyncWorker.java:48) [io.airbyte-airbyte-workers-0.14.4-alpha.jar:?]
    at io.airbyte.workers.wrappers.OutputConvertingWorker.run(OutputConvertingWorker.java:44) [io.airbyte-airbyte-workers-0.14.4-alpha.jar:?]
    at io.airbyte.workers.wrappers.JobOutputSyncWorker.run(JobOutputSyncWorker.java:32) [io.airbyte-airbyte-workers-0.14.4-alpha.jar:?]
    at io.airbyte.scheduler.WorkerRun.lambda$new$0(WorkerRun.java:53) [io.airbyte-airbyte-scheduler-0.14.4-alpha.jar:?]
    at io.airbyte.scheduler.WorkerRun.call(WorkerRun.java:61) [io.airbyte-airbyte-scheduler-0.14.4-alpha.jar:?]
    at io.airbyte.scheduler.WorkerRun.call(WorkerRun.java:42) [io.airbyte-airbyte-scheduler-0.14.4-alpha.jar:?]
    at io.airbyte.commons.concurrency.LifecycledCallable.execute(LifecycledCallable.java:114) [io.airbyte-airbyte-commons-0.14.4-alpha.jar:?]
    at io.airbyte.commons.concurrency.LifecycledCallable.call(LifecycledCallable.java:98) [io.airbyte-airbyte-commons-0.14.4-alpha.jar:?]
    at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
    at java.lang.Thread.run(Thread.java:832) [?:?]



## Generated SQL File

    root@198c64c78203:/tmp/workspace/14/0# cat build/run/airbyte_utils/models/generated/airbyte_views/_AIRBYTE_AIRBYTE/AB2_ADDRESSES_2.sql
    
      create or replace  view "OPENBRIDGE_DATABASE"._AIRBYTE_AIRBYTE."AB2_ADDRESSES_2"  as (
    
    
    
    select
        _AIRBYTE_CUSTOMER_1_HASHID,
        cast(ID as
        int
    ) as ID,
        cast(ZIP as
        varchar
    ) as ZIP,
        cast(CITY as
        varchar
    ) as CITY,
        cast(NAME as
        varchar
    ) as NAME,
        cast(PHONE as
        varchar
    ) as PHONE,
        cast(COMPANY as
        varchar
    ) as COMPANY,
        cast(COUNTRY as
        varchar
    ) as COUNTRY,
        cast(default as boolean) as DEFAULT,
        cast(ADDRESS1 as
        varchar
    ) as ADDRESS1,
        cast(ADDRESS2 as
        varchar
    ) as ADDRESS2,
        cast(PROVINCE as
        varchar
    ) as PROVINCE,
        cast(LAST_NAME as
        varchar
    ) as LAST_NAME,
        cast(FIRST_NAME as
        varchar
    ) as FIRST_NAME,
        cast(CUSTOMER_ID as
        int
    ) as CUSTOMER_ID,
        cast(COUNTRY_CODE as
        varchar
    ) as COUNTRY_CODE,
        cast(COUNTRY_NAME as
        varchar
    ) as COUNTRY_NAME,
        cast(PROVINCE_CODE as
        varchar
    ) as PROVINCE_CODE,
        _airbyte_emitted_at
    from "OPENBRIDGE_DATABASE"._AIRBYTE_AIRBYTE."AB1_ADDRESSES_2"
    
    -- ADDRESSES_2 from o/r/d/e/r/s///c/u/s/t/o/m/e/r///a/d/d/r/e/s/s/e/s
      );

**Comment by ChristopheDuong** [comment]
Cross-posting from my answer on the PR back to the issue:

> The PR #2129 was merged to master but normalization is still not released with that fix so you don't see the corrected behavior yet (even if you are using master branch)

> Another big PR on normalization is on its way and will ship the previous fix along with its release here: #2104 whenever that one will be merged to master.
