### ISSUE TITLE
100% CPU utilization on CDC replication from Postgres CDC

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#6003]
## Enviroment
* **Airbyte version**:   0.29.11-alpha
* **OS Version / Instance**: Ubuntu
* **Deployment**: EC2 instance
* **Source Connector and version**: airbyte/source-mysql:0.4.3
* **Destination Connector and version**: airbyte/destination-snowflake:0.3.12
* **Severity**: **High** 
* **Step where error happened**: Sync job

## Current Behavior
100% CPU utilization on the instance and the sync hangs. See the logs: 

[60m_row_table_success_but_hangs.txt](https://github.com/airbytehq/airbyte/files/7151089/60m_row_table_success_but_hangs.txt)

In addition, the user reports 100% CPU utilization on the node 

```
CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
30008d45fded        pedantic_morse      100.76%             851.6MiB / 30.96GiB   2.69%               0B / 0B             226MB / 1GB         38
```

[Slack thread](https://airbytehq.slack.com/archives/C01MFR03D5W/p1629636715470600)

## Expected Behavior
I expect the sync to complete and CPU utilization not to be quite so drastic. 

## Logs
See above

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202102171868563/1202126627595803) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
This is potentially a duplicate of #5754

**Comment by danieldiamond** [comment]
Attempted to retry this after recent developments in airbyte's source + destination connectors. however, no luck. 
I didn't successfully reach the end of the full load i.e. 60M rows but failing after 11M rows
https://airbytehq.slack.com/archives/C01MFR03D5W/p1634262470051300

**Comment by danieldiamond** [comment]
I can confirm that using `STANDARD` loading method works. here's some additional context https://airbytehq.slack.com/archives/C01MFR03D5W/p1634376853105300?thread_ts=1634262470.051300&cid=C01MFR03D5W

you can probably find more in the slack comments on other threads (i've used this table in various attempts for various issues)

**Comment by tuliren** [comment]
@sashaNeshcheret, got it. Thanks for the explanation.

To summarize all the related issues:
- MySQL source
  - Data sync hanging: fixed in #5600
  - 100% CPU usage: this issue
- Snowflake destination
  - S3 staging OOME: fixed in #7074

Based on Daniel's [latest update](https://github.com/airbytehq/airbyte/issues/5277#issuecomment-946678702), the 100% CPU usage issue still exists for the latest MySQL source (`0.4.8`).

**Comment by sashaNeshcheret** [comment]
Thank you @danieldiamond, I will use your scenario with huge db volume, hope I will catch job's hanging.
@tuliren thanks for summarizing, I will move ticket to in progress and play with it.

**Comment by sashaNeshcheret** [comment]
@danieldiamond can you, please, provide logs for last attempts.

**Comment by danieldiamond** [comment]
posted here https://airbytehq.slack.com/archives/C01MFR03D5W/p1634767335269000?thread_ts=1634284099.068600&cid=C01MFR03D5W

**Comment by danieldiamond** [comment]
Confirming this is still occurring with:
**Airbyte version**: 0.30.23-alpha
**OS Version / Instance**: AWS m5.2xlarge
**Deployment:** Docker
**Source Connector and version**: airbyte/source-mysql:0.4.9
**Destination Connector and version**: airbyte/destination-snowflake:0.3.16
**Severity**: Critical
**Step where error happened**: Sync job

**Comment by sherifnada** [comment]
@tuliren mind taking point on this since you're managing the DB rehaul efforts?

**Comment by tuliren** [comment]
Got it.

Please note that we may not have bandwidth to fix all the CDC issues in Q4. They are likely our major focus in Q1 2022.

**Comment by tuliren** [comment]
Although we originally planned to work on database CDC this quarter, our priorities have changed, and unfortunately we won't have the bandwidth to work on CDC this quarter any more. We recommend anyone watching this issue to use the non CDC mode for incremental sync for now.

**Comment by danieldiamond** [comment]
Appreciate the limited resources and existing priorities but suggesting to defer to non-CDC mode for large tables isn't a great alternative. Particularly if users already had existing internal batch migration jobs. Part of Airbyte's draw is ["commoditising DB replication by open-sourcing CDC"](https://www.businesswire.com/news/home/20210630005217/en/Airbyte-Commoditizes-Database-Replication-by-Open-Sourcing-Log-Based-Change-Data-Capture) - I see this issue relating to a core functionality/expectation of using Airbyte so here's to hoping for something next quarter 🤞

**Comment by bleonard** [comment]
It's been awhile for this issue. @danieldiamond, have you tried this recently? We've made many improvements in CDC.

**Comment by danieldiamond** [comment]
@bleonard appreciate you reaching out on this. 
I'd say let's close this out. I think don't think MySQL CDC is GA ready but I also don't think the current issues are linked to this one.

**Comment by bleonard** [comment]
Ok @danieldiamond sounds good. Feel free to ping me on any current issues. We want to make it the best it can be.
