### ISSUE TITLE
[source-xero] Xero source is broken since 2.1.0. No records returned for streams

### ISSUE THREAD

**Issue by absorbb** [airbytehq/airbyte#66667]
### Connector Name

source-xero

### Connector Version

2.1.0 - 2.1.4

### What step the error happened?

During the sync

### Relevant information

Xero source doesn't return any rows since version 2.1.0
It seems to make correct API calls that return payload with data
But no records are produced from these results

Version 2.0.1 works fine

### Relevant log output

```shell
INFO Starting syncing
INFO Marking stream contacts as STARTED
INFO Syncing stream: contacts
DEBUG Making outbound API request: {"url":"https://api.xero.com/api.xro/2.0/Contacts?page_size=100","request_body":"None","headers":"{'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Xero-Tenant-Id': '****', 'Authorization': 'Bearer ****'}"}
DEBUG Receiving response: {"status":"200","body":"{\r\n  \"Id\": \"****\",\r\n  \"Status\": \"OK\",\r\n  \"ProviderName\": \"****\",\r\n  \"DateTimeUTC\": \"\\/Date(1758708209213)\\/\",\r\n  \"Contacts\": [
... CONTACTS DATA ...
]\r\n}","headers":"{'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '105019', 'Server': 'nginx', 'Xero-Correlation-Id': '****', 'X-AppMinLimit-Remaining': '9999', 'X-MinLimit-Remaining': '59', 'X-DayLimit-Remaining': '4993', 'Xero-Tenant-Id': '****', 'Expires': 'Wed, 24 Sep 2025 10:03:29 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Wed, 24 Sep 2025 10:03:29 GMT', 'Connection': 'keep-alive', 'X-Client-TLS-ver': 'tls1.3'}"}
INFO Read 0 records from contacts stream
INFO Marking stream contacts as STOPPED
INFO slice:{"start_time": "2025-01-01T00:00:00+0000", "end_time": "2025-09-24T10:03:28+0000"}
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by Karlostavitch1** [comment]
Same issue,  anyone found a solution beyond rolling back to an earlier version?

**Comment by mahadirz** [comment]
I've raised the PR to resolve the issue https://github.com/airbytehq/airbyte/pull/71340

**Comment by mahadirz** [comment]
@kconnellywsc @DanyloGL

The reason I didn’t reopen the same PR is that, after further testing, I found multiple issues in the manifest config. For example, even with the incremental option enabled, it was still calling the API from scratch on every run. The pagination size can also be increased to 1,000 instead of just 100. In addition, OAuth can support auto-refresh and persist the refresh token for the next run, along with a few other improvements.

I’ve pushed my latest config here if you’d like to take a look:
https://github.com/airbytehq/airbyte/commit/bcf54ce8284cdd4f4b4b2a9c78b7e3f77fe0593b

This is what we’re currently using internally at my company. Feel free to use it, or extend it and submit a proper PR.

**Comment by DanyloGL** [comment]
@mahadirz thank you for your contribution!

**Comment by venomwaqar** [comment]
Can someone help me out? I'm using v2.1.5 and still getting zero records? no error whatsoever
I'm testing with Xero's Demo tenant with OAuth connection.

I can confirm with Xero's UI that it has data - but logs showing zero records are fetched for any table

```
Sync summary: {
  "status" : "completed",
  "recordsSynced" : 0,
  "bytesSynced" : 0,
  "startTime" : 1779826302128,
  "endTime" : 1779826315098,
  "totalStats" : {
    "bytesCommitted" : 0,
    "bytesEmitted" : 0,
    "destinationStateMessagesEmitted" : 8,
    "destinationWriteEndTime" : 1779826314941,
    "destinationWriteStartTime" : 1779826305967,
    "meanSecondsBeforeSourceStateMessageEmitted" : 0,
    "maxSecondsBeforeSourceStateMessageEmitted" : 2,
    "maxSecondsBetweenStateMessageEmittedandCommitted" : 1,
    "meanSecondsBetweenStateMessageEmittedandCommitted" : 0,
    "recordsEmitted" : 0,
    "recordsCommitted" : 0,
    "recordsFilteredOut" : 0,
    "bytesFilteredOut" : 0,
    "replicationEndTime" : 1779826314947,
    "replicationStartTime" : 1779826302128,
    "sourceReadEndTime" : 1779826310981,
    "sourceReadStartTime" : 1779826305982,
    "sourceStateMessagesEmitted" : 8
  },
  "streamStats" : [ {
    "streamName" : "contacts",
    "stats" : {
      "bytesCommitted" : 0,
      "bytesEmitted" : 0,
      "estimatedBytes" : 0,
      "estimatedRecords" : 0,
      "recordsEmitted" : 0,
      "recordsCommitted" : 0,
      "recordsFilteredOut" : 0,
      "bytesFilteredOut" : 0
    }
  }, {
    "streamName" : "bank_transfers",
    "stats" : {
      "bytesCommitted" : 0,
      "bytesEmitted" : 0,
      "estimatedBytes" : 0,
      "estimatedRecords" : 0,
      "recordsEmitted" : 0,
      "recordsCommitted" : 0,
      "recordsFilteredOut" : 0,
      "bytesFilteredOut" : 0
    }
  }, {
    "streamName" : "accounts",
    "stats" : {
      "bytesCommitted" : 0,
      "bytesEmitted" : 0,
      "estimatedBytes" : 0,
      "estimatedRecords" : 0,
      "recordsEmitted" : 0,
      "recordsCommitted" : 0,
      "recordsFilteredOut" : 0,
      "bytesFilteredOut" : 0
    }
  }, {
    "streamName" : "invoices",
    "stats" : {
      "bytesCommitted" : 0,
      "bytesEmitted" : 0,
      "estimatedBytes" : 0,
      "estimatedRecords" : 0,
      "recordsEmitted" : 0,
      "recordsCommitted" : 0,
      "recordsFilteredOut" : 0,
      "bytesFilteredOut" : 0
    }
  } ],
  "performanceMetrics" : { }
}```

```

**Comment by davewalkercornes** [comment]
This is definitely to do with the way Xero has changed how permissions are defined.  Any new credentials generated after March 2026 use the new Xero scopes.   The current airbyte connector only allows for utilisation of old permission scopes which are not in use for new credentials - hence zero rows and no permission warnings.

**Comment by ksuleyman1** [comment]
> This is definitely to do with the way Xero has changed how permissions are defined. Any new credentials generated after March 2026 use the new Xero scopes. The current airbyte connector only allows for utilisation of old permission scopes which are not in use for new credentials - hence zero rows and no permission warnings.

Agree. 

Are any fixes anticipated?
