### ISSUE TITLE
Source MySQL CDC: sync failed when has null value in `created_at` column

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#6884]
## Enviroment
Is this your first time deploying Airbyte: No
OS Version / Instance:  c5.4xlarge
Memory / Disk:  (16vCPU and 32GB ram)
Deployment: AWS Kubernetes
 Airbyte Version: 0.30.1-alpha
Step: Initial Sync
Description: We are trying to replicate from Aurora RDS MySQL Reporting Replica with Binary Logs (CDC) to AWS S3, and we have some tables that have datetime fields that either have 0 or null values.  We run into Java Heap errors like the following:

[Slack convo](https://airbytehq.slack.com/archives/C01MFR03D5W/p1633045225041800)

## Current Behavior
![image](https://user-images.githubusercontent.com/5154322/136486123-3001343d-150f-43d6-9e43-9a09a82938fa.png)

## Expected Behavior
*Tell us what should happen.*

## Logs
[logs-165-0 masked.txt](https://github.com/airbytehq/airbyte/files/7307893/logs-165-0.masked.txt)

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by DoNotPanicUA** [comment]
After many attempts, we still can't reproduce this case on our instance. The CDC connector always processes values without any errors. No matter which type is it zero value or simple null.
So, I see here two directions where we still can do something:
1) Fully reproduce user environment. The issue is definitely somewhere inside the Debezium driver and we need to localize that specific case when it doesn't work. @tylerdelange could you provide the DDL SQL script of the table and if it is possible the data row mentioned in your error message? (If you need help with the script, feel free to ask)
2) As the issue is definitely inside the Debezium, we can try the latest version of the driver. I will prepare the MySQL source version with the latest Debezuim driver and push it for testing. There is a high chance that it's already fixed indirectly.

**Comment by DoNotPanicUA** [comment]
I've pushed the testing version of MySql source under version `0.4.9b`. The source uses the 1.7.1 Debezium version.
@tylerdelange please update your MySql source version and try your sync one more time.

**Comment by chris-leigh-dignifi** [comment]
`-- sample table
CREATE TABLE activity_roles
(
    id          INT AUTO_INCREMENT
        PRIMARY KEY,
    role_id     INT      NULL,
    activity_id INT      NULL,
    created_at  DATETIME NOT NULL,
    updated_at  DATETIME NOT NULL
);

CREATE INDEX index_activity_roles_on_activity_id
    ON activity_roles (activity_id);

CREATE INDEX index_activity_roles_on_role_id
    ON activity_roles (role_id);

INSERT INTO cfs.activity_roles (id, role_id, activity_id, created_at, updated_at)
VALUES  (21, 239, 21, '2013-09-11 04:11:57', '2013-09-11 04:11:57'),
        (22, 239, 23, '2013-09-11 04:11:57', '2013-09-11 04:11:57'),
        (23, 239, 25, '2013-09-11 04:11:57', '2013-09-11 04:11:57'),
        (24, 240, 21, '2013-09-11 04:12:22', '2013-09-11 04:12:22'),
        (25, 240, 25, '2013-09-11 04:12:22', '2013-09-11 04:12:22'),
        (26, 241, 23, '2013-09-11 04:12:50', '2013-09-11 04:12:50'),
        (27, 242, 21, '2013-09-11 04:28:54', '2013-09-11 04:28:54'),
        (28, 242, 22, '2013-09-11 04:28:54', '2013-09-11 04:28:54'),
        (29, 242, 23, '2013-09-11 04:28:54', '2013-09-11 04:28:54'),
        (30, 242, 24, '2013-09-11 04:28:54', '2013-09-11 04:28:54'),
        (31, 242, 25, '2013-09-11 04:28:54', '2013-09-11 04:28:54'),
        (32, 238, 21, '2013-10-04 14:43:47', '2013-10-04 14:43:47'),
        (33, 238, 23, '2013-10-04 14:43:47', '2013-10-04 14:43:47'),
        (34, 238, 25, '2013-10-04 14:43:47', '2013-10-04 14:43:47'),
        (37, 235, 21, '2013-10-09 15:08:31', '2013-10-09 15:08:31'),
        (38, 235, 23, '2013-10-09 15:08:31', '2013-10-09 15:08:31'),
        (39, 235, 25, '2013-10-09 15:08:31', '2013-10-09 15:08:31'),
        (40, 238, 26, '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
        (41, 242, 26, '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
        (42, 237, 21, '2014-03-14 21:25:41', '2014-03-14 21:25:41'),
        (43, 237, 23, '2014-03-14 21:25:41', '2014-03-14 21:25:41'),
        (44, 237, 25, '2014-03-14 21:25:41', '2014-03-14 21:25:41'),
        (45, 237, 26, '2014-03-14 21:25:41', '2014-03-14 21:25:41'),
        (46, 239, 26, '2014-03-25 16:40:20', '2014-03-25 16:40:20'),
        (47, 235, 22, '2014-04-24 15:35:03', '2014-04-24 15:35:03'),
        (48, 235, 24, '2014-04-24 15:35:03', '2014-04-24 15:35:03'),
        (49, 235, 26, '2014-04-24 15:35:03', '2014-04-24 15:35:03'),
        (50, 245, 23, '2014-05-01 20:20:21', '2014-05-01 20:20:21'),
        (55, 237, 27, '2014-05-21 18:48:55', '2014-05-21 18:48:55'),
        (56, 238, 27, '2014-05-21 18:49:05', '2014-05-21 18:49:05'),
        (57, 241, 27, '2014-05-21 18:49:17', '2014-05-21 18:49:17'),
        (58, 245, 27, '2014-05-21 18:49:26', '2014-05-21 18:49:26'),
        (59, 237, 28, '2014-06-09 23:18:25', '2014-06-09 23:18:25'),
        (60, 238, 28, '2014-06-09 23:18:50', '2014-06-09 23:18:50'),
        (61, 241, 28, '2014-06-09 23:18:59', '2014-06-09 23:18:59'),
        (62, 245, 28, '2014-06-09 23:19:07', '2014-06-09 23:19:07'),
        (63, 246, 21, '2015-05-19 02:05:31', '2015-05-19 02:05:31'),
        (64, 246, 23, '2015-05-19 02:05:31', '2015-05-19 02:05:31'),
        (65, 246, 25, '2015-05-19 02:05:31', '2015-05-19 02:05:31'),
        (66, 246, 26, '2015-05-19 02:05:31', '2015-05-19 02:05:31'),
        (67, 246, 27, '2015-05-19 02:05:31', '2015-05-19 02:05:31'),
        (68, 246, 28, '2015-05-19 02:05:31', '2015-05-19 02:05:31'),
        (69, 258, 21, '2015-05-19 02:06:47', '2015-05-19 02:06:47'),
        (70, 258, 23, '2015-05-19 02:06:47', '2015-05-19 02:06:47'),
        (71, 258, 25, '2015-05-19 02:06:47', '2015-05-19 02:06:47'),
        (72, 258, 26, '2015-05-19 02:06:47', '2015-05-19 02:06:47'),
        (73, 258, 27, '2015-05-19 02:06:47', '2015-05-19 02:06:47'),
        (74, 258, 28, '2015-05-19 02:06:47', '2015-05-19 02:06:47'),
        (75, 261, 21, '2015-05-19 02:09:10', '2015-05-19 02:09:10'),
        (76, 261, 23, '2015-05-19 02:09:10', '2015-05-19 02:09:10'),
        (77, 261, 25, '2015-05-19 02:09:10', '2015-05-19 02:09:10'),
        (78, 261, 26, '2015-05-19 02:09:10', '2015-05-19 02:09:10'),
        (79, 261, 27, '2015-05-19 02:09:10', '2015-05-19 02:09:10'),
        (80, 261, 28, '2015-05-19 02:09:10', '2015-05-19 02:09:10'),
        (81, 259, 21, '2015-05-19 02:09:35', '2015-05-19 02:09:35'),
        (82, 259, 23, '2015-05-19 02:09:35', '2015-05-19 02:09:35'),
        (83, 259, 25, '2015-05-19 02:09:35', '2015-05-19 02:09:35'),
        (84, 259, 26, '2015-05-19 02:09:35', '2015-05-19 02:09:35'),
        (85, 259, 27, '2015-05-19 02:09:35', '2015-05-19 02:09:35'),
        (86, 259, 28, '2015-05-19 02:09:35', '2015-05-19 02:09:35'),
        (87, 236, 29, '2016-02-08 20:03:36', '2016-02-08 20:03:36'),
        (88, 282, 21, '2020-02-06 15:07:34', '2020-02-06 15:07:34'),
        (89, 282, 25, '2020-02-06 15:07:43', '2020-02-06 15:07:43');`

**Comment by christopher-leigh** [comment]
```SQL
-- sample table
CREATE TABLE activity_roles
(
    id          INT AUTO_INCREMENT
        PRIMARY KEY,
    role_id     INT      NULL,
    activity_id INT      NULL,
    created_at  DATETIME NOT NULL,
    updated_at  DATETIME NOT NULL
);

CREATE INDEX index_activity_roles_on_activity_id
    ON activity_roles (activity_id);

CREATE INDEX index_activity_roles_on_role_id
    ON activity_roles (role_id);

INSERT INTO cfs.activity_roles (id, role_id, activity_id, created_at, updated_at)
VALUES  (21, 239, 21, '2013-09-11 04:11:57', '2013-09-11 04:11:57'),
        (22, 239, 23, '2013-09-11 04:11:57', '2013-09-11 04:11:57'),
        (23, 239, 25, '2013-09-11 04:11:57', '2013-09-11 04:11:57'),
        (24, 240, 21, '2013-09-11 04:12:22', '2013-09-11 04:12:22'),
        (25, 240, 25, '2013-09-11 04:12:22', '2013-09-11 04:12:22'),
        (26, 241, 23, '2013-09-11 04:12:50', '2013-09-11 04:12:50'),
        (27, 242, 21, '2013-09-11 04:28:54', '2013-09-11 04:28:54'),
        (28, 242, 22, '2013-09-11 04:28:54', '2013-09-11 04:28:54'),
        (29, 242, 23, '2013-09-11 04:28:54', '2013-09-11 04:28:54'),
        (30, 242, 24, '2013-09-11 04:28:54', '2013-09-11 04:28:54'),
        (31, 242, 25, '2013-09-11 04:28:54', '2013-09-11 04:28:54'),
        (32, 238, 21, '2013-10-04 14:43:47', '2013-10-04 14:43:47'),
        (33, 238, 23, '2013-10-04 14:43:47', '2013-10-04 14:43:47'),
        (34, 238, 25, '2013-10-04 14:43:47', '2013-10-04 14:43:47'),
        (37, 235, 21, '2013-10-09 15:08:31', '2013-10-09 15:08:31'),
        (38, 235, 23, '2013-10-09 15:08:31', '2013-10-09 15:08:31'),
        (39, 235, 25, '2013-10-09 15:08:31', '2013-10-09 15:08:31'),
        (40, 238, 26, '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
        (41, 242, 26, '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
        (42, 237, 21, '2014-03-14 21:25:41', '2014-03-14 21:25:41'),
        (43, 237, 23, '2014-03-14 21:25:41', '2014-03-14 21:25:41'),
        (44, 237, 25, '2014-03-14 21:25:41', '2014-03-14 21:25:41'),
        (45, 237, 26, '2014-03-14 21:25:41', '2014-03-14 21:25:41'),
        (46, 239, 26, '2014-03-25 16:40:20', '2014-03-25 16:40:20'),
        (47, 235, 22, '2014-04-24 15:35:03', '2014-04-24 15:35:03'),
        (48, 235, 24, '2014-04-24 15:35:03', '2014-04-24 15:35:03'),
        (49, 235, 26, '2014-04-24 15:35:03', '2014-04-24 15:35:03'),
        (50, 245, 23, '2014-05-01 20:20:21', '2014-05-01 20:20:21'),
        (55, 237, 27, '2014-05-21 18:48:55', '2014-05-21 18:48:55'),
        (56, 238, 27, '2014-05-21 18:49:05', '2014-05-21 18:49:05'),
        (57, 241, 27, '2014-05-21 18:49:17', '2014-05-21 18:49:17'),
        (58, 245, 27, '2014-05-21 18:49:26', '2014-05-21 18:49:26'),
        (59, 237, 28, '2014-06-09 23:18:25', '2014-06-09 23:18:25'),
        (60, 238, 28, '2014-06-09 23:18:50', '2014-06-09 23:18:50'),
        (61, 241, 28, '2014-06-09 23:18:59', '2014-06-09 23:18:59'),
        (62, 245, 28, '2014-06-09 23:19:07', '2014-06-09 23:19:07'),
        (63, 246, 21, '2015-05-19 02:05:31', '2015-05-19 02:05:31'),
        (64, 246, 23, '2015-05-19 02:05:31', '2015-05-19 02:05:31'),
        (65, 246, 25, '2015-05-19 02:05:31', '2015-05-19 02:05:31'),
        (66, 246, 26, '2015-05-19 02:05:31', '2015-05-19 02:05:31'),
        (67, 246, 27, '2015-05-19 02:05:31', '2015-05-19 02:05:31'),
        (68, 246, 28, '2015-05-19 02:05:31', '2015-05-19 02:05:31'),
        (69, 258, 21, '2015-05-19 02:06:47', '2015-05-19 02:06:47'),
        (70, 258, 23, '2015-05-19 02:06:47', '2015-05-19 02:06:47'),
        (71, 258, 25, '2015-05-19 02:06:47', '2015-05-19 02:06:47'),
        (72, 258, 26, '2015-05-19 02:06:47', '2015-05-19 02:06:47'),
        (73, 258, 27, '2015-05-19 02:06:47', '2015-05-19 02:06:47'),
        (74, 258, 28, '2015-05-19 02:06:47', '2015-05-19 02:06:47'),
        (75, 261, 21, '2015-05-19 02:09:10', '2015-05-19 02:09:10'),
        (76, 261, 23, '2015-05-19 02:09:10', '2015-05-19 02:09:10'),
        (77, 261, 25, '2015-05-19 02:09:10', '2015-05-19 02:09:10'),
        (78, 261, 26, '2015-05-19 02:09:10', '2015-05-19 02:09:10'),
        (79, 261, 27, '2015-05-19 02:09:10', '2015-05-19 02:09:10'),
        (80, 261, 28, '2015-05-19 02:09:10', '2015-05-19 02:09:10'),
        (81, 259, 21, '2015-05-19 02:09:35', '2015-05-19 02:09:35'),
        (82, 259, 23, '2015-05-19 02:09:35', '2015-05-19 02:09:35'),
        (83, 259, 25, '2015-05-19 02:09:35', '2015-05-19 02:09:35'),
        (84, 259, 26, '2015-05-19 02:09:35', '2015-05-19 02:09:35'),
        (85, 259, 27, '2015-05-19 02:09:35', '2015-05-19 02:09:35'),
        (86, 259, 28, '2015-05-19 02:09:35', '2015-05-19 02:09:35'),
        (87, 236, 29, '2016-02-08 20:03:36', '2016-02-08 20:03:36'),
        (88, 282, 21, '2020-02-06 15:07:34', '2020-02-06 15:07:34'),
        (89, 282, 25, '2020-02-06 15:07:43', '2020-02-06 15:07:43');
```

**Comment by marcosmarxm** [comment]
@DoNotPanicUA could you try to reproduce the error again and solve this issue?

**Comment by alexchouraki** [comment]
Hello,
I'm having the same error.
Using the 0.4.9b version of the MySQL connector doesn't solve the issue, I'm still getting the exact same error even though Debezium was upgraded.

Please find the logs attached:
`2022-01-20 17:00:42 source > 2022-01-20 17:00:42 ERROR i.d.r.TableSchemaBuilder(lambda$createValueGenerator$5):269 - {dbz.connectorContext=snapshot, dbz.connectorName=prestashopprod, dbz.connectorType=MySQL} - Failed to properly convert data value for 'prestashopprod.ps_order_serial_number.date_import' of type DATE for row [17581, 0, [115, 101, 114, 105, 97, 108, 95, 110, 117, 109, 98, 101, 114], null, [98, 108, 95, 110, 117, 109, 98, 101, 114], null, null]:
2022-01-20 17:00:42 source > org.apache.kafka.connect.errors.DataException: Invalid value: null used for required field: "date_import", schema type: STRING
2022-01-20 17:00:42 source > 	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:220) ~[connect-api-2.8.1.jar:?]
2022-01-20 17:00:42 source > 	at org.apache.kafka.connect.data.Struct.put(Struct.java:216) ~[connect-api-2.8.1.jar:?]
2022-01-20 17:00:42 source > 	at io.debezium.relational.TableSchemaBuilder.lambda$createValueGenerator$5(TableSchemaBuilder.java:265) ~[debezium-core-1.7.1.Final.jar:1.7.1.Final]
2022-01-20 17:00:42 source > 	at io.debezium.relational.TableSchema.valueFromColumnData(TableSchema.java:141) ~[debezium-core-1.7.1.Final.jar:1.7.1.Final]`

For now, I'll be forgetting about the incremental sync and using the overwrite only!

**Comment by vincent-infostrux** [comment]
Hi, is there a known workaround for this problem? I'm seeing the same error under similar circumstances (MySQL -> Snowflake). I've also tried v0.4.9b of the connector with no success.

**Comment by DoNotPanicUA** [comment]
Update.
I've drilled down into this topic and have something to share.
After I put the previous comment, I realized that CDC should use any columns to trach an increment. It should use an internal commit pointer (different naming for different databases). So, it means that, unfortunately, the Debezium has an issue and the MySQL connector works a bit differently than described in the doc.
The good news is that we can fix it on our site without affecting the incremental logic. In case of mandatory attribute and Zero-date value, we will put the epoch date.

**Comment by alexchouraki** [comment]
Okay, so just to be sure I understand well, a future version of the connector, that will automatically manage Null or Zero-date values, should eventually solve the issue, right?
Thanks a lot, that's great news!

**Comment by DoNotPanicUA** [comment]
I've tested the PR locally, and the issue is gone.
So, be strong! The fix is coming :wink:

**Comment by DoNotPanicUA** [comment]
The fix is released. Please try version `0.5.4`

**Comment by christopher-leigh** [comment]
I can confirm that this fixed the issue! Thank you so much!
